name: flutter_simple_dependency_injection
description: A super simple dependency injection implementation for flutter that behaves like any normal IOC container and does not rely on mirrors
version: 1.0.3
homepage: https://github.com/jonsamwell/flutter_simple_dependency_injection

dependencies:

dev_dependencies:
  test:
  pedantic:

environment:
  sdk: ">=2.0.0 <3.0.0"
